name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: tonasodji/sarif/.github/workflows/reuse.yml@main

  call-workflow-passing-data:
    uses: tonasodji/sarif/.github/workflows/reuse.yml@main
    with:
      username: sodji98
    secrets:
      token: ${{ secrets.TOKEN }}
