name: "client"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: run
      run: ls
    
  client:
    uses: tonasodji/sarif/.github/workflows/server.yml@main

